# .github/workflows/main.yml

name: Node.js CI 

on: 
  push:
    branches: [ main, develop ] # Chỉ chạy trên các nhánh này
  pull_request: # Kích hoạt khi có pull request
    branches: [ main, develop ] # Chỉ chạy khi PR nhắm vào các nhánh này

jobs:
  build-and-test: 
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies 
        run: npm ci

      - name: Run linters 
        run: npm run lint 

      - name: Build project 
        run: npm run build

      - name: Run tests
        run: npm test
